### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by joosm** [pyrk/pyrk#32]
I got the following error message when I tried "python setup.py install"
"error: package directory 'pyrk/utils' does not exist"

**Comment by katyhuff** [comment]
Hi there. The pyrk build system needs some work. You should be able to run
in place at this time, using driver.py but a robust build system is going
to be part of the next release. It's a known issue :
https://github.com/pyrk/pyrk/issues/26.

**Comment by joosm** [comment]
I just realized that there is "utilities" folder.  When I renamed the folder "utils", the error message was gone.

**Comment by katyhuff** [comment]
You may find just changing the name of the folder causes runtime issues .
Python uses folder names in namespace definitions.

**Comment by joosm** [comment]
It seems 'park.utils' in "setup.py" should be updated to 'pyrk.utilities'

**Comment by katyhuff** [comment]
Yes, among other issues with setup.py, that is true. 
Feel free to make a pull request. I can address this later this weekend, but like I said, the complete overhaul of setup.py will be part of the next release.

**Comment by katyhuff** [comment]
closed with #33
