### ISSUE TITLE
Review pylint for useful code quality checks

### ISSUE THREAD

**Issue by gbremer** [pyrk/pyrk#53]
Review pylint for useful code quality checks. First glance shows a lot of noise -- too short variable names, class methods that can be refactored to functions, formatting. A useful error that has popped up is "dangerous defaults" where functions parameter defaults were set to lists or dicts -- these parameters can hold onto values like static variables. It is better to default the items to None and then massage them to an empty list or dict in the function.

**Comment by gbremer** [comment]
Push request with some fixes from pylint --

* Replace dangerous parameter defaults
* Superfluous assert parens
* Fixing indents
* Splitting lines with multiple statements

**Comment by katyhuff** [comment]
I think this was closed with #54 !
