### ISSUE TITLE
ModuleError when running git clone of Pyrk

### ISSUE THREAD

**Issue by Theo21S** [pyrk/pyrk#85]
I've tried to execute the correct installation program python setup.py install, however this is the error I get.
`C:\Python310\python.exe: can't open file 'C:\\Users\\WSMALLS\\OneDrive - University of South Carolina\\Nuclear Reactor Project\\setup.py': [Errno 2] No such file or directory`

When I run the input.py from the examples default this is the error I get in return. 
"Traceback (most recent call last):
  File "c:\Users\WSMALLS\OneDrive - University of South Carolina\Nuclear Reactor Project\pyrk\examples\default\input.py", line 1, in <module>
    from pyrk.utilities.ur import units
ModuleNotFoundError: No module named 'pyrk'"

I have pyrk repository within the same file as everything else, I don't know why python is having a hard time recognizing/retrieving the information from it.

@katyhuff

**Comment by ElijahCapps** [comment]
What command are you running when you attempt the install and input?

**Comment by Theo21S** [comment]
When I attempt install I run `python setup.py install` but it gives me a no directory found error. I tried moving setup.py to another directory but no such luck.

If I did not answer the question the way that I run these commands is in the python terminal located on VSC.

**Comment by ElijahCapps** [comment]
I'm not sure how it may work with VSC, but maybe you need to change your directory in the terminal to where setup.py is located? In my process, I used Condas base environment in Windows command prompt, I changed my directory to where setup.py was located, and ran the script. From there, I could run input files, tests, and more.

**Comment by Theo21S** [comment]
I've never tried that. I'll try it and let you know if I get an error.

**Comment by Theo21S** [comment]
`(base) root@COMECH-0083:/Nuclear Reactor Project/pyrk/pyrk# python setup.py install
Traceback (most recent call last):
  File "/Nuclear Reactor Project/pyrk/pyrk/setup.py", line 5, in <module>
    from pyrk.ver import get_git_version
ModuleNotFoundError: No module named 'pyrk''`

This is the new error I get.

**Comment by ElijahCapps** [comment]
I think setup.py should be outside of the second pyrk folder, but within the first, so that it can use all of the information within the second pyrk folder. Try moving it to the first pyrk folder, running it again, and see what happens.

**Comment by Theo21S** [comment]
`(base) root@COMECH-0083:/Nuclear Reactor Project/pyrk/pyrk# python setup.py install
Traceback (most recent call last):
  File "/Nuclear Reactor Project/pyrk/pyrk/setup.py", line 5, in <module>
    from pyrk.ver import get_git_version
ModuleNotFoundError: No module named 'pyrk'`

This is the new error. I don't know why it doesn't recognize where to find files within pyrk. Since the directory is named pyrk but the folder that it's trying to call from has the same name. Would that cause confusion with the program?

**Comment by Theo21S** [comment]
I can send you a video of the errors I a getting in real time if that would help.

**Comment by ElijahCapps** [comment]
That could possibly help. The path to setup.py from your earlier post still shows its in the second pyrk folder. Place setup.py within the first pyrk folder so that it looks like "Nuclear Reactor Project/pyrk/setup.py".

**Comment by Theo21S** [comment]
This is a link to the video of how I set it up. It looks like I switched the folders on the original directory, I forgot I copied the pyrk library so I could run it through linux

Video: https://www.kapwing.com/w/sY7Gh0a4Yr

**Comment by Theo21S** [comment]
Update: I had to type `python3` instead of `python` Here are the results:

`root@COMECH-0083:/Nuclear Reactor Project/pyrk# python3 setup.py install
/usr/lib/python3/dist-packages/setuptools/dist.py:507: UserWarning: The version specified ('0.2.dev369f5ed') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
running install
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.2.dev369f5ed is an invalid version and will not be supported in a future release
  warnings.warn(
running bdist_egg
running egg_info
writing pyrk.egg-info/PKG-INFO
writing dependency_links to pyrk.egg-info/dependency_links.txt
writing requirements to pyrk.egg-info/requires.txt
writing top-level names to pyrk.egg-info/top_level.txt
reading manifest file 'pyrk.egg-info/SOURCES.txt'
writing manifest file 'pyrk.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pyrk
copying build/lib/pyrk/density_model.py -> build/bdist.linux-x86_64/egg/pyrk
copying build/lib/pyrk/convective_model.py -> build/bdist.linux-x86_64/egg/pyrk
creating build/bdist.linux-x86_64/egg/pyrk/inp
copying build/lib/pyrk/inp/__init__.py -> build/bdist.linux-x86_64/egg/pyrk/inp
copying build/lib/pyrk/inp/validation.py -> build/bdist.linux-x86_64/egg/pyrk/inp
copying build/lib/pyrk/inp/sim_info.py -> build/bdist.linux-x86_64/egg/pyrk/inp
creating build/bdist.linux-x86_64/egg/pyrk/materials
copying build/lib/pyrk/materials/liquid_material.py -> build/bdist.linux-x86_64/egg/pyrk/materials
copying build/lib/pyrk/materials/ss316.py -> build/bdist.linux-x86_64/egg/pyrk/materials
copying build/lib/pyrk/materials/material.py -> build/bdist.linux-x86_64/egg/pyrk/materials
copying build/lib/pyrk/materials/graphite.py -> build/bdist.linux-x86_64/egg/pyrk/materials
copying build/lib/pyrk/materials/kernel.py -> build/bdist.linux-x86_64/egg/pyrk/materials
copying build/lib/pyrk/materials/sodium.py -> build/bdist.linux-x86_64/egg/pyrk/materials
copying build/lib/pyrk/materials/trisos.py -> build/bdist.linux-x86_64/egg/pyrk/materials
copying build/lib/pyrk/materials/__init__.py -> build/bdist.linux-x86_64/egg/pyrk/materials
copying build/lib/pyrk/materials/flibe.py -> build/bdist.linux-x86_64/egg/pyrk/materials
copying build/lib/pyrk/materials/fhrfuel.py -> build/bdist.linux-x86_64/egg/pyrk/materials
copying build/lib/pyrk/materials/sfrmetal.py -> build/bdist.linux-x86_64/egg/pyrk/materials
creating build/bdist.linux-x86_64/egg/pyrk/db
copying build/lib/pyrk/db/database.py -> build/bdist.linux-x86_64/egg/pyrk/db
copying build/lib/pyrk/db/descriptions.py -> build/bdist.linux-x86_64/egg/pyrk/db
copying build/lib/pyrk/db/__init__.py -> build/bdist.linux-x86_64/egg/pyrk/db
copying build/lib/pyrk/ver.py -> build/bdist.linux-x86_64/egg/pyrk
creating build/bdist.linux-x86_64/egg/pyrk/utilities
copying build/lib/pyrk/utilities/ur.py -> build/bdist.linux-x86_64/egg/pyrk/utilities
copying build/lib/pyrk/utilities/plotter.py -> build/bdist.linux-x86_64/egg/pyrk/utilities
copying build/lib/pyrk/utilities/__init__.py -> build/bdist.linux-x86_64/egg/pyrk/utilities
copying build/lib/pyrk/utilities/logger.py -> build/bdist.linux-x86_64/egg/pyrk/utilities
copying build/lib/pyrk/utilities/exceptions.py -> build/bdist.linux-x86_64/egg/pyrk/utilities
copying build/lib/pyrk/reactivity_insertion.py -> build/bdist.linux-x86_64/egg/pyrk
creating build/bdist.linux-x86_64/egg/pyrk/data
copying build/lib/pyrk/data/decay_heat.py -> build/bdist.linux-x86_64/egg/pyrk/data
copying build/lib/pyrk/data/__init__.py -> build/bdist.linux-x86_64/egg/pyrk/data
copying build/lib/pyrk/data/precursors.py -> build/bdist.linux-x86_64/egg/pyrk/data
copying build/lib/pyrk/__init__.py -> build/bdist.linux-x86_64/egg/pyrk
copying build/lib/pyrk/neutronics.py -> build/bdist.linux-x86_64/egg/pyrk
copying build/lib/pyrk/th_system.py -> build/bdist.linux-x86_64/egg/pyrk
copying build/lib/pyrk/th_component.py -> build/bdist.linux-x86_64/egg/pyrk
copying build/lib/pyrk/driver.py -> build/bdist.linux-x86_64/egg/pyrk
copying build/lib/pyrk/timer.py -> build/bdist.linux-x86_64/egg/pyrk
byte-compiling build/bdist.linux-x86_64/egg/pyrk/density_model.py to density_model.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/convective_model.py to convective_model.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/inp/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/inp/validation.py to validation.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/inp/sim_info.py to sim_info.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/materials/liquid_material.py to liquid_material.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/materials/ss316.py to ss316.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/materials/material.py to material.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/materials/graphite.py to graphite.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/materials/kernel.py to kernel.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/materials/sodium.py to sodium.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/materials/trisos.py to trisos.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/materials/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/materials/flibe.py to flibe.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/materials/fhrfuel.py to fhrfuel.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/materials/sfrmetal.py to sfrmetal.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/db/database.py to database.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/db/descriptions.py to descriptions.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/db/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/ver.py to ver.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/utilities/ur.py to ur.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/utilities/plotter.py to plotter.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/utilities/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/utilities/logger.py to logger.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/utilities/exceptions.py to exceptions.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/reactivity_insertion.py to reactivity_insertion.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/data/decay_heat.py to decay_heat.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/data/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/data/precursors.py to precursors.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/neutronics.py to neutronics.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/th_system.py to th_system.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/th_component.py to th_component.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/driver.py to driver.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyrk/timer.py to timer.cpython-310.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pyrk.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyrk.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyrk.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyrk.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyrk.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
pyrk.__pycache__.driver.cpython-310: module references __file__
creating 'dist/pyrk-0.2.dev369f5ed-py3.10.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pyrk-0.2.dev369f5ed-py3.10.egg
removing '/usr/local/lib/python3.10/dist-packages/pyrk-0.2.dev369f5ed-py3.10.egg' (and everything under it)
creating /usr/local/lib/python3.10/dist-packages/pyrk-0.2.dev369f5ed-py3.10.egg
Extracting pyrk-0.2.dev369f5ed-py3.10.egg to /usr/local/lib/python3.10/dist-packages
pyrk 0.2.dev369f5ed is already the active version in easy-install.pth

Installed /usr/local/lib/python3.10/dist-packages/pyrk-0.2.dev369f5ed-py3.10.egg
Processing dependencies for pyrk===0.2.dev369f5ed
Finished processing dependencies for pyrk===0.2.dev369f5ed`

**Comment by Theo21S** [comment]
Here's what happens when I run one of the examples:

`root@COMECH-0083:/Nuclear Reactor Project/pyrk/examples/default# python3 input.py
Traceback (most recent call last):
  File "/Nuclear Reactor Project/pyrk/examples/default/input.py", line 2, in <module>
    from pyrk import th_component as th
  File "/usr/local/lib/python3.10/dist-packages/pyrk-0.2.dev369f5ed-py3.10.egg/pyrk/th_component.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'`

**Comment by Theo21S** [comment]
UPDATE: After getting all the requirements from requirements.txt here is the new error when running the input file:

`root@COMECH-0083:/Nuclear Reactor Project/pyrk/examples/default# python3 input.py
Traceback (most recent call last):
  File "/Nuclear Reactor Project/pyrk/examples/default/input.py", line 17, in <module>
    alpha_f = -3.8 * units.pcm / units.kelvin
NameError: name 'units' is not defined`

**Comment by ElijahCapps** [comment]
Did you run it through driver.py? The documentation suggests running an input file like this:

`python /path/to/pyrk/driver.py --infile=input.py --plotdir=out`

Your output graphs and plots should then be found in "out" in the main pyrk folder.

Also, you should run nosetests to see if your installation of PyRK passes its own tests:

`nosetests pyrk/tests`

**Comment by Theo21S** [comment]
Do I have to run it from a specific directory? It doesn't recoginze the command "nosetest"



`root@COMECH-0083:~# nosetests pyrk/tests
Command 'nosetests' not found, did you mean:
  command 'nosetests3' from deb python3-nose (1.3.7-8)
Try: apt install <deb name>`

`root@COMECH-0083:/Nuclear Reactor Project/pyrk/examples/default# nosetests pyrk/tests
Command 'nosetests' not found, did you mean:
  command 'nosetests3' from deb python3-nose (1.3.7-8)
Try: apt install <deb name>`

**Comment by Theo21S** [comment]
Can `python3 /Nuclear Reactor Project/pyrk/pyrk/driver.py --
infile=input.py --plotdir=out` Be run from the directory with driver.py?

**Comment by Theo21S** [comment]
After running the `python3 /Nuclear Reactor Project/pyrk/pyrk/driver.py -- infile=input.py --plotdir=out` It says 

root@COMECH-0083:/# python3 /Nuclear\ Reactor\ Project/pyrk/pyrk/driver.py --infile=input.py --plotdir=out
Traceback (most recent call last):
  File "/Nuclear Reactor Project/pyrk/pyrk/driver.py", line 284, in <module>
    main(args, curr_dir)
  File "/Nuclear Reactor Project/pyrk/pyrk/driver.py", line 239, in main
    infile = load_infile(args.infile)
  File "/Nuclear Reactor Project/pyrk/pyrk/driver.py", line 232, in load_infile
    infile = importlib.import_module(file_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'input'
---------------------------------------------------------------------------------------


root@COMECH-0083:/# python3 /Nuclear\ Reactor\ Project/pyrk/pyrk/driver.py --infile=infile --plotdir=out
Traceback (most recent call last):
  File "/Nuclear Reactor Project/pyrk/pyrk/driver.py", line 284, in <module>
    main(args, curr_dir)
  File "/Nuclear Reactor Project/pyrk/pyrk/driver.py", line 239, in main
    infile = load_infile(args.infile)
  File "/Nuclear Reactor Project/pyrk/pyrk/driver.py", line 232, in load_infile
    infile = importlib.import_module(file_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'infile'

**Comment by Theo21S** [comment]
Looks Like I get the same error running from the place where driver.py is located

`root@COMECH-0083:/Nuclear Reactor Project/pyrk/pyrk# python3 driver.py --infile=input.py --plotdir=out
Traceback (most recent call last):
  File "/Nuclear Reactor Project/pyrk/pyrk/driver.py", line 284, in <module>
    main(args, curr_dir)
  File "/Nuclear Reactor Project/pyrk/pyrk/driver.py", line 239, in main
    infile = load_infile(args.infile)
  File "/Nuclear Reactor Project/pyrk/pyrk/driver.py", line 232, in load_infile
    infile = importlib.import_module(file_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'input'`

**Comment by katyhuff** [comment]
Earlier, it was suggested you run nosetests. The command is "nosetests" plural. You appear to have typed "nosetest".

I'm interested to see the output of running the tests. To see it, you should run `nosetests pyrk/tests` .

**Comment by katyhuff** [comment]
What happened when you tried installing nosestest in order to run the tests?

**Comment by Theo21S** [comment]
root@COMECH-0083:/Nuclear Reactor Project/pyrk/examples/default# nosetests pyrk/tests
Command 'nosetests' not found, did you mean:
  command 'nosetests3' from deb python3-nose (1.3.7-8)
Try: apt install <deb name>

Looks like I'll need to install nosetest. Is it a Python installation Package?

**Comment by Theo21S** [comment]
Looks like it was a pip. Here are the results:

root@COMECH-0083:/Nuclear Reactor Project/pyrk/examples/default# nosetests pyrk/tests
Traceback (most recent call last):
  File "/usr/local/bin/nosetests", line 8, in <module>
    sys.exit(run_exit())
  File "/usr/local/lib/python3.10/dist-packages/nose/core.py", line 118, in __init__
    unittest.TestProgram.__init__(
  File "/usr/lib/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/local/lib/python3.10/dist-packages/nose/core.py", line 179, in parseArgs
    self.createTests()
  File "/usr/local/lib/python3.10/dist-packages/nose/core.py", line 193, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames)
  File "/usr/local/lib/python3.10/dist-packages/nose/loader.py", line 481, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
  File "/usr/lib/python3.10/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.10/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/lib/python3.10/dist-packages/nose/loader.py", line 459, in loadTestsFromName
    return suite([
  File "/usr/local/lib/python3.10/dist-packages/nose/suite.py", line 423, in __call__
    tests = self.wrapTests(tests)
  File "/usr/local/lib/python3.10/dist-packages/nose/suite.py", line 541, in wrapTests
    if isinstance(tests, collections.Callable) or isinstance(tests, unittest.TestSuite):
AttributeError: module 'collections' has no attribute 'Callable'
root@COMECH-0083:/Nuclear Reactor Project/pyrk/examples/default#

**Comment by ElijahCapps** [comment]
https://stackoverflow.com/questions/76579315/nosetests-is-not-running-for-some-reason

This suggests you should try using Pynose instead.

**Comment by Theo21S** [comment]
I got a new error after installing Pynose:

root@COMECH-0083:/#  nosetests pyrk/tests
E
======================================================================
ERROR: Failure: OSError (No such file /pyrk/tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nose/failure.py", line 38, in runTest
    raise self.exc_class(self.exc_val)
OSError: No such file /pyrk/tests

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)

**Comment by ElijahCapps** [comment]
Are you running from the main PyRK folder?

**Comment by Theo21S** [comment]
When running from the main folder here is the result:

(base) root@COMECH-0083:/Nuclear Reactor Project/pyrk# nosetests pyrk/tests
....................50.0 kelvin
............
----------------------------------------------------------------------
Ran 32 tests in 2.090s

OK
(base) root@COMECH-0083:/Nuclear Reactor Project/pyrk#

**Comment by Theo21S** [comment]
hopefully that's okay. Here's what happens after running the previous command

```pre
(base) root@COMECH-0083:/Nuclear Reactor Project/pyrk/pyrk/db# python3 /Nuclear\ Reactor\ Project/pyrk/pyrk/driver.py --infile=infile --plotdir=out
Traceback (most recent call last):
  File "/Nuclear Reactor Project/pyrk/pyrk/driver.py", line 14, in <module>
    from pyrk.db import database
ModuleNotFoundError: No module named 'pyrk.db'

**Comment by Theo21S** [comment]
> Did you run setup.py?

Yes I did

> nosetests pyrk/tests

Here

**Comment by Theo21S** [comment]
Then

```pre
root@COMECH-0083:/Nuclear Reactor Project/pyrk# python3 /Nuclear\ Reactor\ Project/pyrk/pyrk/driver.py --infile=infile --plotdir=out
Traceback (most recent call last):
  File "/Nuclear Reactor Project/pyrk/pyrk/driver.py", line 284, in <module>
    main(args, curr_dir)
  File "/Nuclear Reactor Project/pyrk/pyrk/driver.py", line 239, in main
    infile = load_infile(args.infile)
  File "/Nuclear Reactor Project/pyrk/pyrk/driver.py", line 232, in load_infile
    infile = importlib.import_module(file_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'infile'

**Comment by ElijahCapps** [comment]
--infile needs an argument, which is your input file (whichever example you may want to run). It should look like `--infile=input.py`

**Comment by Theo21S** [comment]
> --infile needs an argument, which is your input file (whichever example you may want to run). It should look like `--infile=input.py`

I tried to run that before but it still gave me an error

```pre
root@COMECH-0083:/Nuclear Reactor Project/pyrk/examples/default# python3 /Nuclear\ Reactor\ Project/pyrk/pyrk/driver.py --infile=input.py --plotdir=out
Traceback (most recent call last):
  File "/Nuclear Reactor Project/pyrk/pyrk/driver.py", line 284, in <module>
    main(args, curr_dir)
  File "/Nuclear Reactor Project/pyrk/pyrk/driver.py", line 239, in main
    infile = load_infile(args.infile)
  File "/Nuclear Reactor Project/pyrk/pyrk/driver.py", line 232, in load_infile
    infile = importlib.import_module(file_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Nuclear Reactor Project/pyrk/examples/default/input.py", line 17, in <module>
    alpha_f = -3.8 * units.pcm / units.kelvin
NameError: name 'units' is not defined
root@COMECH-0083:/Nuclear Reactor Project/pyrk/examples/default#

**Comment by Theo21S** [comment]
Running the command anywhere except `/Nuclear Reactor Project/pyrk/examples/default` gives me an error of:

`ModuleNotFoundError: No module named 'input'`

@ElijahCapps

**Comment by ElijahCapps** [comment]
What I remember worked for me was moving the input.py file into the same directory that contains driver.py and running from there.

**Comment by Theo21S** [comment]
It's the last part that I keep getting an error on:

`alpha_f = -3.8 * units.pcm / units.kelvin`
`NameError: name 'units' is not defined`

```pre
Traceback (most recent call last):
  File "/Nuclear Reactor Project/pyrk/pyrk/driver.py", line 284, in <module>
    main(args, curr_dir)
  File "/Nuclear Reactor Project/pyrk/pyrk/driver.py", line 239, in main
    infile = load_infile(args.infile)
  File "/Nuclear Reactor Project/pyrk/pyrk/driver.py", line 232, in load_infile
    infile = importlib.import_module(file_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Nuclear Reactor Project/pyrk/pyrk/input.py", line 17, in <module>
    alpha_f = -3.8 * units.pcm / units.kelvin
NameError: name 'units' is not defined

**Comment by ElijahCapps** [comment]
Which example are you running?

**Comment by Theo21S** [comment]
It still gives the same error for some reason. I use python3 because my terminal doesn't recognize the command `python`

```pre
root@COMECH-0083:/Nuclear Reactor Project/pyrk/pyrk# python3 driver.py --infile=input.py --plotdir=out
Traceback (most recent call last):
    alpha_f = -3.8 * units.pcm / units.kelvin
NameError: name 'units' is not defined

**Comment by ElijahCapps** [comment]
Your pyrk directory has a utilities folder with ur.py in it, right?

**Comment by Theo21S** [comment]
> Your pyrk directory has a utilities folder with ur.py in it, right?

Yes
```pre
root@COMECH-0083:/Nuclear Reactor Project/pyrk/pyrk/utilities# ls
__init__.py  __pycache__  exceptions.py  logger.py  plotter.py  tests  ur.py

**Comment by Theo21S** [comment]
@katyhuff

**Comment by Theo21S** [comment]
Update: after Uninstalling, renaming, and reinstalling the Git Clone of Pyrk. Running PyRK through my Ubuntu terminal. Using the command `python3 setup.py install` in the location of setup.py. And using `python3 /path/to/pyrk/driver.py --infile=input.py --plotdir=out` in the location of the input.py file, it finally works.



@katyhuff 
@ElijahCapps

**Comment by ElijahCapps** [comment]
Glad you got it figured out! I'm sorry I couldn't be of more help earlier.

**Comment by Theo21S** [comment]
> Glad you got it figured out! I'm sorry I couldn't be of more help earlier.



> Glad you got it figured out! I'm sorry I couldn't be of more help earlier.

None sense you helped a lot. Thank you so much!
